version: '2'
services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: changeMe
        volumes:
            - ./backup/var/lib/mysql:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        links:
            - db:mysql
        environment: 
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: changeMe
            PMA_HOST: mysql
    web:
        build: apache
        environment:
            - TERM=xterm
        depends_on:
            - db
        volumes:
            - ./public_html:/var/www/html
            - ./backup/virtual_hosts:/virtual_hosts
        links:
            - db:mysql
